### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tabrizbala1989** [hiifeng/V2ray-for-Doprax#10]
when launch in doprax say this error :

Step 1/16 : FROM nginx:latest

---> 9eee96112def

Step 2/16 : MAINTAINER ifeng <https://t.me/HiaiFeng>

---> Using cache

---> 265d9894e91a

Step 3/16 : EXPOSE 80

---> Using cache

---> d5346e5d2f74

Step 4/16 : USER root

---> Using cache

---> 956412bac544

Step 5/16 : RUN apt-get update && apt-get install -y supervisor wget unzip

---> Running in be2065b5dfab

Err:1 http://deb.debian.org/debian bullseye InRelease Temporary failure resolving 'deb.debian.org'

Err:2 http://deb.debian.org/debian-security bullseye-security InRelease Temporary failure resolving 'deb.debian.org'

Err:3 http://deb.debian.org/debian bullseye-updates InRelease Temporary failure resolving 'deb.debian.org'

Reading package lists...

[91mW: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease Temporary failure resolving 'deb.debian.org' W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease Temporary failure resolving 'deb.debian.org' W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease Temporary failure resolving 'deb.debian.org' W: Some index files failed to download. They have been ignored, or old ones used instead. [0m

Reading package lists...

Building dependency tree...

Reading state information...

[91mE: Unable to locate package supervisor E: Unable to locate package wget E: Unable to locate package unzip [0m

The command '/bin/sh -c apt-get update && apt-get install -y supervisor wget unzip' returned a non-zero code: 100

**Comment by hiifeng** [comment]
According to the error message you sent, the host failed to resolve the deb.debian.org domain name during the build process. Please try again later.
