### ISSUE TITLE
problem in doprax

### ISSUE THREAD

**Issue by vpsservermail** [hiifeng/V2ray-for-Doprax#12]
i get error 
[91mE: Unable to locate package supervisor E: Unable to locate package wget E: Unable to locate package unzip [0m
The command '/bin/sh -c apt-get update && apt-get install -y supervisor wget unzip' returned a non-zero code: 100

Process failed
when i try to run my app in doprax

**Comment by hiifeng** [comment]
Due to a high influx of users, the service of doprax is currently unstable, please try again later.
