### ISSUE TITLE
部署没有错误，也可以访问nginx页面，就是wss链接部署

### ISSUE THREAD

**Issue by raomx** [hiifeng/V2ray-for-Doprax#49]
用了cloudflare和DNS，通过自己的域名可以访问nginx页面，当wss连接不上，为啥？

**Comment by raomx** [comment]
https://hello.roliver.cc/

**Comment by hiifeng** [comment]
1、能通过域名访问到nginx的欢迎页面，说明nginx工作正常。
2、https://hello.roliver.cc/后面加上伪装路径访问，如果显示Bad Request，说明v2ray工作正常。
3、在客户端v2ray里导入https://github.com/hiifeng/V2ray-for-Doprax/blob/main/example.txt 中的example节点连接，将localhost修改为你的域名，修改UUID，修改伪装路径后即可。
4、如果还不行，检测本地环境。

**Comment by raomx** [comment]
> https://hello.roliver.cc/

https://hello.roliver.cc/vl
Connection timed out Error code 522

**Comment by raomx** [comment]
Doprax_hostname="hellolidc.eu-iiqsdfthygfv.dopraxrocks.net";

**Comment by raomx** [comment]
应该是cloudflare的代理配置出错了，有没有相关的文档？

**Comment by raomx** [comment]
自己域名配置的环节出错了，能告诉一下怎么弄吗？

**Comment by hbqclh** [comment]
同样的问题，百思不得其解，你说的123都没问题，4点，我其它的节点都可以正常使用。。。。

> 1、能通过域名访问到nginx的欢迎页面，说明nginx工作正常。 2、[https://hello.roliver.cc/后面加上伪装路径访问，如果显示Bad](https://hello.roliver.cc/%E5%90%8E%E9%9D%A2%E5%8A%A0%E4%B8%8A%E4%BC%AA%E8%A3%85%E8%B7%AF%E5%BE%84%E8%AE%BF%E9%97%AE%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%98%BE%E7%A4%BABad) Request，说明v2ray工作正常。 3、在客户端v2ray里导入https://github.com/hiifeng/V2ray-for-Doprax/blob/main/example.txt 中的example节点连接，将localhost修改为你的域名，修改UUID，修改伪装路径后即可。 4、如果还不行，检测本地环境。
