### ISSUE TITLE
Doprax is unstable..

### ISSUE THREAD

**Issue by mrsoltani078** [hiifeng/V2ray-for-Doprax#63]
Hi and thanks for the code.
Guys is there any other way that we could use your code?
Like deno deploy is kinda like doprax can you guys make this code available for deno??

**Comment by hiifeng** [comment]
Sorry, there are too many container platforms and I can't quite remember. As far as I know, there are other people in the group who have worked on the xray project for deno.com. Additionally, deno has strict restrictions on proxy projects. For more details, please ask other people in the Telegram group. Thank you. https://t.me/HiaiFeng
