### ISSUE TITLE
一个神奇的现象

### ISSUE THREAD

**Issue by hhhhhhh68568** [hiifeng/V2ray-for-Doprax#72]
使用doprax搭建好v2ray后,ping域名可以ping上,但节点不能用,大概被墙了.
于是按照hifeng's blog 用cf的pages反代,
随后v2rayN显示,延迟163ms 但是测速timeout.
我打开youtube,发现能够流畅观看1080p的视频
但当我将节点复制到手机时,居然telegram都无法连接
和pc端云泥之别

**Comment by hiifeng** [comment]
已经能打开youtube，说明节点是正常的，分析手机的网络环境，有无软件冲突等。
