### ISSUE TITLE
Cloudflare CDN

### ISSUE THREAD

**Issue by bahmanworld** [hiifeng/V2ray-for-Doprax#75]
Hi @hiifeng , thanks for this great repo
i want to connect the doprax domain (or custom domain) to cloudflare cdn.
is it possible? if yes, is there some tutorial to do this?

**Comment by ProjMingSTU** [comment]
Definitely possible. I find it from creater's blog,sadly,it's written in Chinese(If you can't read Chinese).[here](https://www.hicairo.com/post/59.html)

**Comment by hiifeng** [comment]
> 绝对有可能。我从 creater 的博客上找到的，遗憾的是，它是用中文写的（如果你看不懂中文）。[这里](https://www.hicairo.com/post/59.html)

You can try to use the browser's google translate plug-in.

**Comment by bahmanworld** [comment]
> Definitely possible. I find it from creater's blog,sadly,it's written in Chinese(If you can't read Chinese).[here](https://www.hicairo.com/post/59.html)

Thanks @ProjMingSTU , unfortunately i can't read chiness but as @hiifeng mentioned i will use google translate chrome extenstion to translate to english.

Thanks again guys
Hope works...
Best Regards
