### ISSUE TITLE
默认配置后，网站证书过期，导致cfpages不能正常运行

### ISSUE THREAD

**Issue by Miaooo92** [hiifeng/V2ray-for-Doprax#83]
Doprax.com默认域名被墙，使用科技在浏览器打开默认域名可以看到证书已过期。
尝试配置cfpages反向代理，部署完成后，通过cf反代域名打开报错：
Invalid SSL certificate ， Error code 526
页面显示报错原因是“源服务器无有效SSL证书“。

大大能否提供解决办法：
让Doprax能够正常更新证书？
或者  让CF能够忽略证书错误？

**Comment by hiifeng** [comment]
由于大量用户使用，doprax服务器超过负载，目前不是很稳定。请使用其他PaaS平台，稍后再试。
